// sha256.h - minimal SHA-256 for bare-metal (no libc deps beyond uint types).
// Used to verify the admin password hash generated by tools/admin_hash.py.
// Reference: FIPS 180-4 (public domain algorithm).
#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t state[8];
    uint64_t bitlen;
    uint8_t  buf[64];
    uint32_t buflen;
} nefu_sha256_ctx;

void nefu_sha256_init(nefu_sha256_ctx* c);
void nefu_sha256_update(nefu_sha256_ctx* c, const void* data, uint32_t len);
void nefu_sha256_final(nefu_sha256_ctx* c, uint8_t out[32]);

// Convenience: hash data -> 32-byte digest.
void nefu_sha256(const void* data, uint32_t len, uint8_t out[32]);

// Format digest as 64 lowercase hex chars into out[65].
void nefu_sha256_hex(const uint8_t digest[32], char out[65]);

#ifdef __cplusplus
}
#endif
